jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$' 
  
server:
  port: 8081
#  error:
#    whitelabel:
#      enabled: false
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: root
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dilect: org.hibernate.dialect.PostgreSQLDialect 
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false