package com.example.microservices.userservice.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Transient;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "Details about the User")
@Entity
public class User {

	@Id
	@GeneratedValue
	@ApiModelProperty(notes = "Autogenerated id of the User")
	private int id;

	@ApiModelProperty(notes = "Name of the User")
	private String name;

	@ApiModelProperty(notes = "Password must be 8 digits and contain 1 alphabet, 1 number and 1 special charecter")
	private String password;

	@Transient
	private Integer port;

	public User() {
		super();
	}

	public User(int id, String name, String password) {
		super();
		this.id = id;
		this.name = name;
		this.password = password;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getPort() {
		return port;
	}

	public void setPort(Integer port) {
		this.port = port;
	}

}
